/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-18 05:36:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productRegisterModal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!-- The ProductRegister Modal -->\r\n");
      out.write("<div class=\"modal\" id=\"productRegister\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t<div class=\"modal-content\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal Header -->\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<h3 class=\"modal-title\">상품 등록</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal body -->\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<form onsubmit=\"return productRegisterCheck();\" class=\"forms-sample\" action=\"/product/productRegister\" method=\"post\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputUsername2\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">상품 이름</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"product_name\" id=\"product_name_register\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputEmail2\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">상품 판매가</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" name=\"product_price\" id=\"product_price_register\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputMobile\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">상품 수량</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" name=\"product_qty\" id=\"product_qty_register\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputPassword2\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">상품 종류</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"product_category\" id=\"product_category_register\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary mr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">등록</font>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button data-dismiss=\"modal\" type=\"button\" class=\"btn btn-success\">닫기</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End ProductRegister Modal -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tfunction productRegisterCheck() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar product_name = $('#product_name_register').val();\r\n");
      out.write("\t\tvar nameCheck = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\tdata : {product_name : product_name},\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\turl : \"/product/productNameCheck\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(result) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tnameCheck = result;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($.trim($(\"#product_name_register\").val()) != $(\"#product_name_register\").val()) {\r\n");
      out.write("\t\t      alert(\"앞,뒤 공백을 지워주세요.\");\r\n");
      out.write("\t\t      $(\"#product_name_register\").val(\"\");\r\n");
      out.write("\t\t      $(\"#product_name_register\").focus();\r\n");
      out.write("\t\t      return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(nameCheck > 0) {\r\n");
      out.write("\t\t\talert(\"이미 있는 상품입니다.\");\r\n");
      out.write("\t\t\t $(\"#product_name_register\").val(\"\");\r\n");
      out.write("\t\t     $(\"#product_name_register\").focus();\r\n");
      out.write("\t\t     return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($.trim($(\"#product_category_register\").val()) != $(\"#product_category_register\").val()) {\r\n");
      out.write("\t\t      alert(\"앞,뒤 공백을 지워주세요.\");\r\n");
      out.write("\t\t      $(\"#product_category_register\").val(\"\");\r\n");
      out.write("\t\t      $(\"#product_category_register\").focus();\r\n");
      out.write("\t\t      return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#product_price_register\").val() <= 0) {\r\n");
      out.write("\t\t\talert(\"판매가를 정해주세요\");\r\n");
      out.write("\t\t\t$(\"#product_price_register\").val(\"\");\r\n");
      out.write("\t\t    $(\"#product_price_register\").focus();\r\n");
      out.write("\t\t    return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#product_qty_register\").val() <= 0) {\r\n");
      out.write("\t\t\talert(\"수량을 정해주세요\");\r\n");
      out.write("\t\t\t$(\"#product_qty_register\").val(\"\");\r\n");
      out.write("\t\t    $(\"#product_qty_register\").focus();\r\n");
      out.write("\t\t    return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
