/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-18 05:38:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.userView;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/userView/../includes/userHeader.jsp", Long.valueOf(1571376690954L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Comic Clerk</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resources/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resources/vendors/base/vendor.bundle.base.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resources/vendors/datatables.net-bs4/dataTables.bootstrap4.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom Fonts -->\r\n");
      out.write("<link href=\"/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"/resources/vendor/simple-line-icons/css/simple-line-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core JavaScript -->\r\n");
      out.write("<script src=\"/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Plugin JavaScript -->\r\n");
      out.write("<script src=\"/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/base/vendor.bundle.base.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/datatables.net/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/datatables.net-bs4/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/vendors/base/vendor.bundle.base.css\">\r\n");
      out.write("<link rel=\"stylesheet\"href=\"/resources/vendors/datatables.net-bs4/dataTables.bootstrap4.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom scripts for this template -->\r\n");
      out.write("<script src=\"/resources/js/stylish-portfolio.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/off-canvas.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/hoverable-collapse.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/template.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/dashboard.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/data-table.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/sockjs/1/sockjs.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/userWebsocket.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"/resources/css/stylish-portfolio.min.css?ver=1\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".content-wrapper {\r\n");
      out.write("\tpadding-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<div class=\"main-penal\">\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div style=\"background-color: #37363a; height: 150px;\">\r\n");
      out.write("\t\t\t\t<img src=\"/resources/images/comic_image.png\" alt=\"\" style=\"width: 200px; height: 100px; margin-left:370px; margin-top:20px; float: left \"/>\r\n");
      out.write("\t\t\t\t<div class=\"content-section-heading text-center\" style=\"width: 700px; height: 100px; margin-top:30px; float: left;\"><br/>\r\n");
      out.write("\t\t\t\t\t<h1 style=\"color:white;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ roomNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 번방 홈 &emsp;&emsp; 02:15:39</h1>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t<div style=\"width: 600px; height: 100px; float: right; color:#f4e362; margin-top:60px; font-size: 20px;\">\r\n");
      out.write("\t\t\t\t 회원 수정 \r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t&emsp;<a href=\"/\" style=\"color:#f4e362; font-size: 20px;\">임의 창</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row no-gutters\" style=\"margin-top: 50px;\"> \t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style=\"border: 10px solid #f4e362; width: 1300px; height: 80px; border-radius: 70px / 30px; margin-bottom: 30px;\">\r\n");
      out.write("\t\t\t\t\t여기에 알림이 오도록 할건지 아님 어떻게 할건지 ??!!\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-item\" id=\"userOrderView\"> <span class=\"caption\"> <span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>상품 주문</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-0\">상품을 주문하실 수 있습니다</p>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span> <img class=\"img-fluid\" src=\"/resources/images/orderIcon.png\" alt=\"\" style=\"width:370px; height:250px;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-item\" id=\"userSearchbook\"> <span class=\"caption\"> <span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>도서 검색</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-0\">코믹 서기의 도서를 검색할 수 있습니다</p>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span> <img class=\"img-fluid\" src=\"/resources/images/searchIcon.png\" alt=\"\" style=\"width:370px; height:250px;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-item\" id=\"billModalBtn\"> <span class=\"caption\"> <span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>상세 요금</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-0\">현재 사용한 요금을 보실 수 있습니다</p>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span> <img class=\"img-fluid\" src=\"/resources/images/moneyIcon.png\" alt=\"\" style=\"width:370px; height:250px;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-item\" id=\"userChat\"> <span class=\"caption\"> <span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>채팅 하기</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-0\">실시간 대화를 나눌 수 있습니다</p>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span> <img class=\"img-fluid\" src=\"/resources/images/chatIcon.png\" alt=\"\" style=\"width:370px; height:250px;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-item\" id=\"userBoard\"> <span class=\"caption\"> <span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>건의 게시판</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-0\">건의 사항을 적는 게시판입니다</p>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span> <img class=\"img-fluid\" src=\"/resources/images/boardIcon.png\" alt=\"\" style=\"width:370px; height:250px;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\"> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-item\" href=\"#\"> <span class=\"caption\"> <span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>사용 종료</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-0\">사용 종료를 하면 로그아웃되고 결제 페이지로 넘어갑니다</p>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span> <img class=\"img-fluid\" src=\"/resources/images/exitIcon.png\" alt=\"\" style=\"width:370px; height:250px;\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "billModal.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "productBillModal.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- hidden form -->\r\n");
      out.write("\t<form id=\"operForm\"></form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tvar operForm = $(\"#operForm\");\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#userOrderView\").on(\"click\", function(e){\r\n");
      out.write("\t\toperForm.attr(\"method\", \"get\");\r\n");
      out.write("\t\toperForm.attr(\"action\",\"/userView/order\");\r\n");
      out.write("\t\toperForm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#userChat\").on(\"click\", function(e){\r\n");
      out.write("\t\toperForm.attr(\"method\", \"get\");\r\n");
      out.write("\t\toperForm.attr(\"action\",\"/userView/chatting\");\r\n");
      out.write("\t\toperForm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#userSearchbook\").on(\"click\", function(e){\r\n");
      out.write("\t\toperForm.attr(\"method\", \"get\");\r\n");
      out.write("\t\toperForm.attr(\"action\",\"/SearchBook/searchList\");\r\n");
      out.write("\t\toperForm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#userBoard\").on(\"click\", function(e){\r\n");
      out.write("\t\toperForm.attr(\"method\", \"get\");\r\n");
      out.write("\t\toperForm.attr(\"action\",\"/userView/board/boardList\");\r\n");
      out.write("\t\toperForm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#billModalBtn\").on(\"click\", function(e){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: 'get',\r\n");
      out.write("\t\t\turl: '/userView/userBill?userId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Memberlogin.MEMBER_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("\t\t\tdataType: 'json',\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t$('#productBill').attr('value',data.product_bill);\r\n");
      out.write("\t\t\t\t$('#roomBill').attr('value',data.room_bill);\r\n");
      out.write("\t\t\t\t$('#totalBill').attr('value',data.total_bill);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#productBillModalBtn\").click(function() {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: 'get',\r\n");
      out.write("\t\t\t\turl: '/userView/userProductBill?userId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Memberlogin.MEMBER_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("\t\t\t\tdataType: 'json',\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t$(\"#productBillTbody\").html(\"\");\r\n");
      out.write("\t\t            var str = '<tr>';\r\n");
      out.write("\t\t            $.each(data , function(i){\r\n");
      out.write("\t\t            \tvar date = new Date(data[i].order_time); var month = date.getMonth() + 1; \r\n");
      out.write("\t\t                str += '<td>' + date.getFullYear() + \"-\" + (month.toString().length > 1 ? month : \"0\" + month) + \"-\" + date.getDate() +\r\n");
      out.write("\t\t                \"<br>\" + date.getHours() + \" : \" + date.getMinutes() + ' : ' + date.getSeconds() + '</td><td>' + data[i].product_name + '</td><td>' + data[i].order_qty + '</td><td>' + data[i].order_bill + '</td>';\r\n");
      out.write("\t\t                str += '</tr>';\r\n");
      out.write("\t\t           });\r\n");
      out.write("\t\t           $(\"#productBillTbody\").append(str);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t/* $(\"#productBillModal\").modal('show').css({\r\n");
      out.write("\t\t\t    'margin-top': function () { //vertical centering\r\n");
      out.write("\t\t\t        return -($(this).height() / 100);\r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\t    'margin-left': function () { //Horizontal centering\r\n");
      out.write("\t\t\t        return -($(this).width() / 100);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t}); */\r\n");
      out.write("\t\t\t$(\"#productBillModal\").show();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('#billModal').show();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
