/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-18 05:38:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.userView;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/userView/../includes/userHeader.jsp", Long.valueOf(1571376690954L));
    _jspx_dependants.put("jar:file:/C:/Users/1027/Documents/GitHub/comic_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comic_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1566355891683L));
    _jspx_dependants.put("jar:file:/C:/Users/1027/Documents/GitHub/comic_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comic_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Comic Clerk</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resources/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resources/vendors/base/vendor.bundle.base.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resources/vendors/datatables.net-bs4/dataTables.bootstrap4.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom Fonts -->\r\n");
      out.write("<link href=\"/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"/resources/vendor/simple-line-icons/css/simple-line-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core JavaScript -->\r\n");
      out.write("<script src=\"/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Plugin JavaScript -->\r\n");
      out.write("<script src=\"/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/base/vendor.bundle.base.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/datatables.net/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/datatables.net-bs4/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/vendors/base/vendor.bundle.base.css\">\r\n");
      out.write("<link rel=\"stylesheet\"href=\"/resources/vendors/datatables.net-bs4/dataTables.bootstrap4.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom scripts for this template -->\r\n");
      out.write("<script src=\"/resources/js/stylish-portfolio.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/off-canvas.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/hoverable-collapse.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/template.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/dashboard.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/data-table.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/sockjs/1/sockjs.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/userWebsocket.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"/resources/css/stylish-portfolio.min.css?ver=1\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url(\"/resources/images/bg-masthead.jpg\");\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content-wrapper {\r\n");
      out.write("\tpadding-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".orderProduct{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("#orderTest {\r\n");
      out.write("\tpadding-top: 10px;\t\r\n");
      out.write("\tpadding-bottom: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write(".container {\r\n");
      out.write("\tbackground-color: #F2D68A;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("\tpadding-top:15px;\r\n");
      out.write("\tcolor: #F3F2EC; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder-top: 1px solid #C49F7B;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("th, td {\r\n");
      out.write("\tborder-bottom: #C49F7B;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("\tbackground-color: #F0C03D;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<div class=\"main-penal\">\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2 text-center\">\r\n");
      out.write("\t\t\t\t\t<h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ roomNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("번방</h1>\r\n");
      out.write("\t\t\t\t\t<p>시간</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"content-section-heading text-center\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"mb-5\">상품 주문</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row no-gutters\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<span> \r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"orderProduct\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t주문목록 <br>\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>상품명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>금액</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>수량</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>취소</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody id=\"tableBody\">\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<label>총금액</label> <input id=\"finalPrice\" readonly> <label>총수량</label> <input id=\"orderQty\" readonly>\r\n");
      out.write("\t\t\t\t\t\t<button onclick=\"productAllDelete();\">전체취소</button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"resultOrder\">상품주문</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- hidden form -->\r\n");
      out.write("\t<form id=\"operForm\"></form>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"modal\" id=\"successModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h4 class=\"modal-title\" id=\"myModalLabel\">주문 완료</h4>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("            </div> \r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" id=\"OK\" class=\"btn btn-primary\">확인</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"/resources/js/userOrderManeger.js?after\"></script> \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tvar categoryValue = \"\";\r\n");
      out.write("\t\tvar orderProduct = $(\".orderProduct\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"button[name = categoryButton]\").on(\"click\", function (e) {\r\n");
      out.write("\t\t\tcategoryValue = $(this).attr('value');\r\n");
      out.write("\t\t\torderProductShow(categoryValue);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction numberWithCommas(x) {\r\n");
      out.write("\t\t    return x.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction orderProductShow(category) {\r\n");
      out.write("\t\t\torderProductService.getList(category, function(data) {\r\n");
      out.write("\t\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(data.length == 0 ) {\r\n");
      out.write("\t\t\t\t\tstr += \" \";\r\n");
      out.write("\t\t\t\t\torderProduct.html(str);\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tstr += '<div class=\"row order-list\">'; \r\n");
      out.write("\t\t\t\tfor(var i = 0, len = data.length || 0; i < len; i++) {\r\n");
      out.write("\t\t\t\t\tvar fileCallPath =  encodeURIComponent( data[i].ORDERVIEW_UPLOADPATH+ \"/\"+data[i].ORDERVIEW_UUID +\"_\"+data[i].ORDERVIEW_FILENAME);\r\n");
      out.write("\t\t\t\t\tstr += \"<div class='col-sm-6 col-md-4 col-lg-3' id='orderTest'>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<br/>\"; \r\n");
      out.write("\t\t\t\t\tstr += \"<img onclick='userProductBtn(\" + data[i].PRODUCT_NUM + \",\\\"\" + data[i].PRODUCT_NAME + \"\\\",\" +data[i].PRODUCT_PRICE + \");' src='/userOrderManager/display?fileName=\" + fileCallPath + \"' width='150' height='200'/>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<br/>\";\r\n");
      out.write("\t\t\t\t\tstr += \"\" + data[i].PRODUCT_NAME;\r\n");
      out.write("\t\t\t\t\tstr += \"<br/>\";\r\n");
      out.write("\t\t\t\t\tstr += \"\" + numberWithCommas(data[i].PRODUCT_PRICE);\r\n");
      out.write("\t\t\t\t\tstr += \"</div>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tstr += \"</div>\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\torderProduct.html(str); \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar orderArray = {};\r\n");
      out.write("\t\tvar qty = 0;\r\n");
      out.write("\t\tvar index = 0;\r\n");
      out.write("\t\tvar tableBody = $(\"#tableBody\");\r\n");
      out.write("\t\tvar finalPrice = $(\"#finalPrice\");\r\n");
      out.write("\t\tvar orderQty = $(\"#orderQty\");\r\n");
      out.write("\r\n");
      out.write("\t\twindow.userProductBtn = function(productNum, productName, productPrice) {\r\n");
      out.write("\t\t\tfor(key in orderArray) {\r\n");
      out.write("\t\t\t\tif(orderArray[key].productNum == productNum) {\r\n");
      out.write("\t\t\t\t\torderArray[key].qty = (orderArray[key].qty + 1);\r\n");
      out.write("\t\t\t\t\torderArray[key].finalPrice = (orderArray[key].qty * orderArray[key].productPrice);\r\n");
      out.write("\t\t\t\t\tconsole.log(orderArray);\r\n");
      out.write("\t\t\t\t\tshowUserProduct();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\torderArray[index] = {productNum: productNum, qty : 1, productName : productName, productPrice : productPrice, finalPrice: productPrice};\r\n");
      out.write("\t\t\tindex += 1;\r\n");
      out.write("\t\t\tconsole.log(orderArray);\r\n");
      out.write("\t\t\tshowUserProduct();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\twindow.productAdd = function(key) {\r\n");
      out.write("\t\t\torderArray[key].qty = (orderArray[key].qty + 1);\r\n");
      out.write("\t\t\torderArray[key].finalPrice = (orderArray[key].qty * orderArray[key].productPrice);\r\n");
      out.write("\t\t\tshowUserProduct();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\twindow.productSub = function(key) {\r\n");
      out.write("\t\t\torderArray[key].qty = (orderArray[key].qty - 1);\r\n");
      out.write("\t\t\torderArray[key].finalPrice = (orderArray[key].qty * orderArray[key].productPrice);\r\n");
      out.write("\t\t\tif(orderArray[key].qty <= 0) {\r\n");
      out.write("\t\t\t\tdelete orderArray[key];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tconsole.log(orderArray);\r\n");
      out.write("\t\t\tshowUserProduct();\r\n");
      out.write("\t\t}\r\n");
      out.write(" \r\n");
      out.write("\t\tfunction showUserProduct(){\r\n");
      out.write("\t\t\tvar finalPriceSum = 0;\r\n");
      out.write("\t\t\tvar qtySum = 0;\r\n");
      out.write("\t\t\tstr = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor(key in orderArray) {\r\n");
      out.write("\t\t\t\tfinalPriceSum += orderArray[key].finalPrice;\r\n");
      out.write("\t\t\t\tqtySum += orderArray[key].qty;\r\n");
      out.write("\t\t\t\tstr += \"<tr>\"\r\n");
      out.write("\t\t\t\tstr += \"<td>\" + orderArray[key].productName + \"</td>\";\r\n");
      out.write("\t\t\t\tstr += \"<td>\" + orderArray[key].finalPrice + \"</td>\";\r\n");
      out.write("\t\t\t\tstr += \"<td>\" + orderArray[key].qty + \"</td>\";\r\n");
      out.write("\t\t\t\tstr += \"<td>[ <a href='#' onclick='productAdd(\" + key + \");'>+</a> , \";\r\n");
      out.write("\t\t\t\tstr += \"<a href='#' onclick='productSub(\" + key + \");'>-</a> ] </td>\";\r\n");
      out.write("\t\t\t\tstr += \"</tr>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfinalPrice.val(finalPriceSum);\r\n");
      out.write("\t\t\torderQty.val(qtySum)\r\n");
      out.write("\t\t\ttableBody.html(str); \t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\twindow.productAllDelete = function(){\r\n");
      out.write("\t\t\tfor(key in orderArray) {\r\n");
      out.write("\t\t\t\tdelete orderArray[key];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tshowUserProduct()\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#resultOrder\").on(\"click\", function(){\r\n");
      out.write("\t\t\tconsole.log(orderArray);\r\n");
      out.write("\t\t\torderProductService.resultOrder(orderArray, function(e) {\r\n");
      out.write("\t\t\t\tproductAllDelete();\r\n");
      out.write("\t\t\t\t$(\"#successModal\").modal(\"show\");\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#OK\").on(\"click\", function(){\r\n");
      out.write("\t\t\t\t$(\"#successModal\").modal(\"hide\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/userView/order.jsp(74,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/userView/order.jsp(74,6) '${ OrderViewVO_List }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ OrderViewVO_List }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/userView/order.jsp(74,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<button class=\"btn btn-secondary btn-rounded btn-fw\" name=\"categoryButton\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ list.orderview_category }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ list.orderview_category }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</button>\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
