/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-18 00:53:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MemberLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/1027/Documents/GitHub/comic_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comic_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1571359426845L));
    _jspx_dependants.put("jar:file:/C:/Users/1027/Documents/GitHub/comic_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comic_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <!-- Required meta tags -->\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <title>Majestic Admin</title>\r\n");
      out.write("  <!-- plugins:css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/vendors/base/vendor.bundle.base.css\">\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  <!-- plugin css for this page -->\r\n");
      out.write("  <!-- End plugin css for this page -->\r\n");
      out.write("  <!-- inject:css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"/resources/images/favicon.png\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container-scroller\">\r\n");
      out.write("    <div class=\"col-lg-4 mx-auto\">\r\n");
      out.write("      <div class=\"auth-form-light text-left py-5 px-4 px-sm-5\" style=\"background-color: RGB(215,215,216,.7); margin-top: 50px;\">\r\n");
      out.write("              <div class=\"brand-logo\">\r\n");
      out.write("                <a href=\"javascript:home()\" ><img src=\"/resources/images/comic_image.png\" alt=\"\" style=\"width: 200px; height: 100px;\"/></a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <form class=\"pt-3\" role=\"form\" name=\"memberlogin\" id=\"memberlogin\" method=\"post\" action=\"/member/MemberLoginPost\" autocomplete=\"off\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control form-control-lg\" id=\"login_MEMBER_ID\" \r\n");
      out.write("                  \t\t name=\"MEMBER_ID\" placeholder=\"아이디를 입력하세요\" autofocus required=\"required\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input type=\"password\" class=\"form-control form-control-lg\" id=\"login_MEMBER_PWD\" \r\n");
      out.write("                  \t\t name=\"MEMBER_PWD\" placeholder=\"비밀번호를 입력하세요\" required=\"required\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"my-2 d-flex justify-content-between\" style=\"float: left;\">\r\n");
      out.write("                  <a data-toggle=\"modal\" href=\"#PasswordModifyModal\" data-backdrop=\"static\" data-keyboard=\"false\" \r\n");
      out.write("                     style=\"color: #007bff;\" class=\"auth-link text-black\">비밀번호 찾기</a>\r\n");
      out.write("                </div><br/><br/>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mt-3\">\r\n");
      out.write("                  <button class=\"btn btn-warning btn- btn-lg font-weight-large auth-form-btn\" \r\n");
      out.write("                  \t\t  style=\"width: 47%; color: white;\" id=\"login\">로그인</button>\r\n");
      out.write("                  <a class=\"btn btn-warning btn- btn-lg font-weight-large auth-form-btn\" \r\n");
      out.write("                  \t style=\"width: 47%; margin-left: 5%; color: white;\" href=\"/member/MemberRegister\" >회원가입</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </form>\r\n");
      out.write("              \r\n");
      out.write("     </div>\r\n");
      out.write("    <!-- content-wrapper ends -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- page-body-wrapper ends -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "PasswordModifyModal.jsp", out, false);
      out.write("\r\n");
      out.write("  <!-- container-scroller -->\r\n");
      out.write("  <!-- plugins:js -->\r\n");
      out.write("  <script src=\"/resources/vendors/base/vendor.bundle.base.js\"></script>\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  <!-- inject:js -->\r\n");
      out.write("  <script src=\"/resources/js/off-canvas.js\"></script>\r\n");
      out.write("  <script src=\"/resources/js/hoverable-collapse.js\"></script>\r\n");
      out.write("  <script src=\"/resources/js/template.js\"></script>\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\tvar roomNum = \"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\t\tconsole.log(roomNum);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t var msg = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t if (msg === \"REGISTERED\") {\r\n");
      out.write("\t\t     alert(\"회원가입이 완료되었습니다. 로그인해주세요~\");\r\n");
      out.write("\t\t } else if (msg == \"FAILURE\") {\r\n");
      out.write("\t\t     alert(\"아이디 또는 비밀번호를 확인해주세요.\");\r\n");
      out.write("\t\t } else if (msg === \"NOMEMBER\") {\r\n");
      out.write("\t\t  alert(\"입력한 정보로 등록된 회원이 없습니다.\")\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t $(\"#login\").on(\"click\", function(e) {\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\t$(\"#memberlogin\").submit();\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t \r\n");
      out.write("\t\tfunction pwdmodify() {\r\n");
      out.write("\t\t  var passwordmodify = $(\"form[name=passwordmodify]\").serialize();\r\n");
      out.write("\t\t\t  $.ajax({\r\n");
      out.write("\t\t\t\t  type : 'post',\r\n");
      out.write("\t\t\t\t  url : '/member/MemberPasswordModify',\r\n");
      out.write("\t\t\t\t  data : passwordmodify,\r\n");
      out.write("\t\t\t\t  success : function(result) {\r\n");
      out.write("\t\t\t\t  \talert(result);\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t   });\r\n");
      out.write("\t\t  }\r\n");
      out.write("\r\n");
      out.write("\t\tfunction home(){\r\n");
      out.write("\t\t\tvar operForm = $(\"#operForm\");\r\n");
      out.write("\r\n");
      out.write("\t\t\toperForm.append(\"<input type='hidden' name='roomNum' value='\" + roomNum + \"'>\");\r\n");
      out.write("\t\t\toperForm.attr(\"method\", \"post\");\r\n");
      out.write("\t\t\toperForm.attr(\"action\",\"/userView/main\");\r\n");
      out.write("\t\t\toperForm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/member/MemberLogin.jsp(75,17) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomNum}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
