/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-18 00:47:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.book;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bookRegisterModal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- The BookRegister Modal -->\r\n");
      out.write("<div class=\"modal\" id=\"bookRegister\">\r\n");
      out.write("\t<div id=\"modal-dialog-register\" class=\"modal-dialog\">\r\n");
      out.write("\t\t<div class=\"modal-content\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal Header -->\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<h3 class=\"modal-title\">책 등록</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Modal body -->\r\n");
      out.write("\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t<div id=\"card-body-register\" class=\"card-body\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputUsername2\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">책 이미지</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t        <div class=\"form-group uploadDiv\">\r\n");
      out.write("\t\t\t\t\t\t            <input type=\"file\" name='uploadFile' id=\"uploadFileRegister\">\r\n");
      out.write("\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t        <div class='uploadResultRegister'> \r\n");
      out.write("\t\t\t\t\t\t        \t<ul>\r\n");
      out.write("\t\t\t\t\t\t          \r\n");
      out.write("\t\t\t\t\t\t        \t</ul>\r\n");
      out.write("\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<form id=\"registerForm\" class=\"forms-sample\" action=\"/book/bookRegister\" role=\"form\" method=\"post\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputUsername2\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">책 이름</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"book_name_register\" type=\"text\" class=\"form-control\" name=\"book_name\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputEmail2\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">책위치</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"book_loc_register\" type=\"text\" class=\"form-control\" name=\"book_loc\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputMobile\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">책출판사</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"book_publisher_register\" type=\"text\" class=\"form-control\" name=\"book_publisher\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword2\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">책 저자</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"book_writer_register\" type=\"text\" class=\"form-control\" name=\"book_writer\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword2\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">책 소개</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"6\" name=\"book_content\" required></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword2\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">책 분류</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"book_category_register\" type=\"text\" class=\"form-control\" name=\"book_category\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword2\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">마지막권</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"book_lastbook_register\" type=\"number\" class=\"form-control\" name=\"book_lastbook\" required>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword2\" class=\"col-sm-3 col-form-label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">연재상태</font>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"book_status_register\" class=\"form-control\" name=\"book_status\">\r\n");
      out.write("\t\t                            <option value=\"연재중\">연재중</option>\r\n");
      out.write("\t\t                            <option value=\"완결\">완결</option>\r\n");
      out.write("\t                            </select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"RegisterSubmitBtn\" type=\"button\" class=\"btn btn-primary mr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">등록</font>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"bookRegisterCloseBtn\" type=\"button\" class=\"btn btn-success\">닫기</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".uploadResultRegister {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground-color: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uploadResultRegister ul {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-flow: row;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uploadResultRegister ul li {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uploadResultRegister ul li img {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#modal-dialog-register{\r\n");
      out.write("    overflow-y: initial !important\r\n");
      out.write("}\r\n");
      out.write("#card-body-register{\r\n");
      out.write("    height: 760px;\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- End BookRegister Modal -->\r\n");
      out.write("\r\n");
      out.write("<!-- <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(e){\r\n");
      out.write("\t  \r\n");
      out.write("\t  var formObj = $(\"form[role='form']\");\r\n");
      out.write("\t  \r\n");
      out.write("\t  $(\"button[name=registerBtn]\").on(\"click\", function(e){\r\n");
      out.write("\r\n");
      out.write("\t    \r\n");
      out.write("\t    e.preventDefault();\r\n");
      out.write("\t    \r\n");
      out.write("\t    console.log(\"submit clicked\");\r\n");
      out.write("\r\n");
      out.write("\t    var book_name = $('#book_name').val();\r\n");
      out.write("\t\tvar nameCheck = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\tdata : {book_name : book_name},\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\turl : \"/book/bookNameCheck\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(result) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tnameCheck = result;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tif($.trim($(\"#book_name\").val()) != $(\"#book_name\").val()) {\r\n");
      out.write("\t\t    alert(\"앞,뒤 공백을 지워주세요.\");\r\n");
      out.write("\t\t    $(\"#book_name\").val(\"\");\r\n");
      out.write("\t\t    $(\"#book_name\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(nameCheck > 0) {\r\n");
      out.write("\t\t\talert(\"이미 있는 책입니다.\");\r\n");
      out.write("\t\t\t$(\"#book_name\").val(\"\");\r\n");
      out.write("\t\t    $(\"#book_name\").focus();\r\n");
      out.write("\t\t    return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($.trim($(\"#book_loc\").val()) != $(\"#book_loc\").val()) {\r\n");
      out.write("\t\t    alert(\"앞,뒤 공백을 지워주세요.\");\r\n");
      out.write("\t\t    $(\"#book_loc\").val(\"\");\r\n");
      out.write("\t\t    $(\"#book_loc\").focus();\r\n");
      out.write("\t\t    return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($.trim($(\"#book_publisher\").val()) != $(\"#book_publisher\").val()) {\r\n");
      out.write("\t\t    alert(\"앞,뒤 공백을 지워주세요.\");\r\n");
      out.write("\t\t    $(\"#book_publisher\").val(\"\");\r\n");
      out.write("\t\t    $(\"#book_publisher\").focus();\r\n");
      out.write("\t\t    return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($.trim($(\"#book_writer\").val()) != $(\"#book_writer\").val()) {\r\n");
      out.write("\t\t    alert(\"앞,뒤 공백을 지워주세요.\");\r\n");
      out.write("\t\t    $(\"#book_writer\").val(\"\");\r\n");
      out.write("\t\t    $(\"#book_writer\").focus();\r\n");
      out.write("\t\t    return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($.trim($(\"#book_category\").val()) != $(\"#book_category\").val()) {\r\n");
      out.write("\t\t    alert(\"앞,뒤 공백을 지워주세요.\");\r\n");
      out.write("\t\t    $(\"#book_category\").val(\"\");\r\n");
      out.write("\t\t    $(\"#book_category\").focus();\r\n");
      out.write("\t\t    return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    \r\n");
      out.write("\t    var str = \"\";\r\n");
      out.write("\t    \r\n");
      out.write("\t    $(\".uploadResult ul li\").each(function(i, obj){\r\n");
      out.write("\t      \r\n");
      out.write("\t      var jobj = $(obj);\r\n");
      out.write("\t      \r\n");
      out.write("\t      console.dir(jobj);\r\n");
      out.write("\t      console.log(\"-------------------------\");\r\n");
      out.write("\t      console.log(jobj.data(\"filename\"));\r\n");
      out.write("\t      \r\n");
      out.write("\t      \r\n");
      out.write("\t      str += \"<input type='hidden' name='attachList[\"+i+\"].fileName' value='\"+jobj.data(\"filename\")+\"'>\";\r\n");
      out.write("\t      str += \"<input type='hidden' name='attachList[\"+i+\"].uuid' value='\"+jobj.data(\"uuid\")+\"'>\";\r\n");
      out.write("\t      str += \"<input type='hidden' name='attachList[\"+i+\"].uploadPath' value='\"+jobj.data(\"path\")+\"'>\";\r\n");
      out.write("\t      str += \"<input type='hidden' name='attachList[\"+i+\"].fileType' value='\"+ jobj.data(\"type\")+\"'>\";\r\n");
      out.write("\t      \r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    console.log(str);\r\n");
      out.write("\t    \r\n");
      out.write("\t    formObj.append(str).submit();\r\n");
      out.write("\t    \r\n");
      out.write("\t  });\r\n");
      out.write("\t\r\n");
      out.write("\t  \r\n");
      out.write("\t  var regex = new RegExp(\"(.*?)\\.(jpg|png)$\");\r\n");
      out.write("\t  var maxSize = 5242880; //5MB\r\n");
      out.write("\t  \r\n");
      out.write("\t  function checkExtension(fileName, fileSize){\r\n");
      out.write("\t    \r\n");
      out.write("\t    if(fileSize >= maxSize){\r\n");
      out.write("\t      alert(\"파일 사이즈 초과\");\r\n");
      out.write("\t      $(\"input[name='uploadFile']\").val(\"\");\r\n");
      out.write("\t      return false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    if(!regex.test(fileName)){\r\n");
      out.write("\t      alert(\"해당 종류의 파일은 업로드할 수 없습니다.\");\r\n");
      out.write("\t      $(\"input[name='uploadFile']\").val(\"\");\r\n");
      out.write("\t      return false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    return true;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  $(\"input[type='file']\").change(function(e){\r\n");
      out.write("\t\r\n");
      out.write("\t    var formData = new FormData();\r\n");
      out.write("\t    \r\n");
      out.write("\t    var inputFile = $(\"input[name='uploadFile']\");\r\n");
      out.write("\t    \r\n");
      out.write("\t    var files = inputFile[0].files;\r\n");
      out.write("\t    \r\n");
      out.write("\t    for(var i = 0; i < files.length; i++){\r\n");
      out.write("\t\r\n");
      out.write("\t      if(!checkExtension(files[i].name, files[i].size) ){\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      formData.append(\"uploadFile\", files[i]);\r\n");
      out.write("\t      \r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t      url: '/uploadAjaxAction',\r\n");
      out.write("\t      processData: false, \r\n");
      out.write("\t      contentType: false,data: \r\n");
      out.write("\t      formData,type: 'POST',\r\n");
      out.write("\t      dataType:'json',\r\n");
      out.write("\t        success: function(result){\r\n");
      out.write("\t          console.log(result); \r\n");
      out.write("\t\t\t  showUploadResult(result); //업로드 결과 처리 함수 \r\n");
      out.write("\t\r\n");
      out.write("\t      }\r\n");
      out.write("\t    }); //$.ajax\r\n");
      out.write("\t    \r\n");
      out.write("\t  });  \r\n");
      out.write("\t  \r\n");
      out.write("\t  function showUploadResult(uploadResultArr){\r\n");
      out.write("\t\t    \r\n");
      out.write("\t    if(!uploadResultArr || uploadResultArr.length == 0){ return; }\r\n");
      out.write("\t    \r\n");
      out.write("\t    var uploadUL = $(\".uploadResult ul\");\r\n");
      out.write("\t    \r\n");
      out.write("\t    var str =\"\";\r\n");
      out.write("\t    \r\n");
      out.write("\t    $(uploadResultArr).each(function(i, obj){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(obj.image){\r\n");
      out.write("\t\t\t\tvar fileCallPath =  encodeURIComponent( obj.uploadPath+ \"/s_\"+obj.uuid +\"_\"+obj.fileName);\r\n");
      out.write("\t\t\t\tstr += \"<li data-path='\"+obj.uploadPath+\"'\";\r\n");
      out.write("\t\t\t\tstr +=\" data-uuid='\"+obj.uuid+\"' data-filename='\"+obj.fileName+\"' data-type='\"+obj.image+\"'\"\r\n");
      out.write("\t\t\t\tstr +\" ><div>\";\r\n");
      out.write("\t\t\t\tstr += \"<span> \"+ obj.fileName+\"</span>\";\r\n");
      out.write("\t\t\t\tstr += \"<button type='button' data-file=\\'\"+fileCallPath+\"\\' \"\r\n");
      out.write("\t\t\t\tstr += \"data-type='image' class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\";\r\n");
      out.write("\t\t\t\tstr += \"<img src='/display?fileName=\"+fileCallPath+\"'>\";\r\n");
      out.write("\t\t\t\tstr += \"</div>\";\r\n");
      out.write("\t\t\t\tstr +\"</li>\";\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tvar fileCallPath =  encodeURIComponent( obj.uploadPath+\"/\"+ obj.uuid +\"_\"+obj.fileName);\t\t\t      \r\n");
      out.write("\t\t\t    var fileLink = fileCallPath.replace(new RegExp(/\\\\/g),\"/\");\r\n");
      out.write("\t\t\t      \r\n");
      out.write("\t\t\t\tstr += \"<li \"\r\n");
      out.write("\t\t\t\tstr += \"data-path='\"+obj.uploadPath+\"' data-uuid='\"+obj.uuid+\"' data-filename='\"+obj.fileName+\"' data-type='\"+obj.image+\"' ><div>\";\r\n");
      out.write("\t\t\t\tstr += \"<span> \"+ obj.fileName+\"</span>\";\r\n");
      out.write("\t\t\t\tstr += \"<button type='button' data-file=\\'\"+fileCallPath+\"\\' data-type='file' \" \r\n");
      out.write("\t\t\t\tstr += \"class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\";\r\n");
      out.write("\t\t\t\tstr += \"<img src='/resources/img/attach.png'></a>\";\r\n");
      out.write("\t\t\t\tstr += \"</div>\";\r\n");
      out.write("\t\t\t\tstr +\"</li>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    uploadUL.append(str);\r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t  $(\".uploadResult\").on(\"click\", \"button\", function(e){\r\n");
      out.write("\t\t    \r\n");
      out.write("\t    console.log(\"delete file\");\r\n");
      out.write("\t      \r\n");
      out.write("\t    var targetFile = $(this).data(\"file\");\r\n");
      out.write("\t    var type = $(this).data(\"type\");\r\n");
      out.write("\t    \r\n");
      out.write("\t    var targetLi = $(this).closest(\"li\");\r\n");
      out.write("\t    \r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t      url: '/deleteFile',\r\n");
      out.write("\t      data: {fileName: targetFile, type:type},\r\n");
      out.write("\t      dataType:'text',\r\n");
      out.write("\t      type: 'POST',\r\n");
      out.write("\t        success: function(result){\r\n");
      out.write("\t           targetLi.remove();\r\n");
      out.write("\t         }\r\n");
      out.write("\t    }); //$.ajax\r\n");
      out.write("\t    $(\"#uploadFile\").val(\"\");\r\n");
      out.write("\t   });\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script> -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
