/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-17 10:43:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class erpIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/Users/1027/Documents/GitHub/comic_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comic_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/./includes/header.jsp", Long.valueOf(1571306725920L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar", Long.valueOf(1569574159109L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1566355891683L));
    _jspx_dependants.put("/WEB-INF/views/./includes/sidebar.jsp", Long.valueOf(1571308918221L));
    _jspx_dependants.put("jar:file:/C:/Users/1027/Documents/GitHub/comic_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comic_project/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1532606274000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Comic Clerk</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resources/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resources/vendors/base/vendor.bundle.base.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resources/vendors/datatables.net-bs4/dataTables.bootstrap4.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/resources/images/favicon.png\" />\r\n");
      out.write("\r\n");
      out.write("<!-- <script src=\"//code.jquery.com/jquery-3.2.1.min.js\"></script> -->\r\n");
      out.write("<script src=\"/resources/vendors/base/vendor.bundle.base.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/datatables.net/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/datatables.net-bs4/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/off-canvas.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/hoverable-collapse.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/template.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/dashboard.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/data-table.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/header.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-scroller\">\r\n");
      out.write("\t\t<!-- partial:partials/_navbar.html -->\r\n");
      out.write("\t\t<nav class=\"navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("\t\t\t<div class=\"navbar-brand-wrapper d-flex justify-content-center\">\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand brand-logo\" href=\"/erp?\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/resources/images/comic_image.png\" alt=\"\" style=\"width: 70px; height: 30px;\"/></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand brand-logo\" href=\"/erp?\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/resources/images/comic_clerk_logo.png\" alt=\"\" style=\"width: 100px; height: 15px;\"/></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<button class=\"navbar-toggler navbar-toggler align-self-center\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" data-toggle=\"minimize\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"mdi mdi-sort-variant\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- hidden form -->\r\n");
      out.write("\t\t\t\t<form id=\"operForm2\"></form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"navbar-menu-wrapper d-flex align-items-center justify-content-end\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("<!-- \t\t\t\t\t<li class=\"nav-item dropdown mr-1\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"messageDropdown\" href=\"#\" data-toggle=\"dropdown\"> \r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"mdi mdi-message-text mx-0\"></i> <span class=\"count\"></span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right navbar-dropdown\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"messageDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"mb-0 font-weight-normal float-left dropdown-header\">Messages</p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"/resources/images/faces/face4.jpg\" alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"profile-pic\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-content flex-grow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"ellipsis font-weight-normal\">David Grey</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"font-weight-light small-text text-muted mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tThe meeting is cancelled</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a class=\"dropdown-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-thumbnail\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"/resources/images/faces/face2.jpg\" alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"profile-pic\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-content flex-grow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"ellipsis font-weight-normal\">Tim Cook</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"font-weight-light small-text text-muted mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tNew product launch</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a class=\"dropdown-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-thumbnail\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"/resources/images/faces/face3.jpg\" alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"profile-pic\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-content flex-grow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"ellipsis font-weight-normal\">Johnson</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"font-weight-light small-text text-muted mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tUpcoming board meeting</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 알림 아이콘 -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown mr-4\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center notification-dropdown\"\r\n");
      out.write("\t\t\t\t\t\tid=\"notificationDropdown\" href=\"#\" data-toggle=\"dropdown\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"mdi mdi-bell mx-0\"></i> <span class=\"count\"></span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right navbar-dropdown\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"notificationDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"mb-0 font-weight-normal float-left dropdown-header\">Notifications</p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"item-icon bg-success\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-information mx-0\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"font-weight-normal\">Application Error</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"font-weight-light small-text mb-0 text-muted\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tJust now</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a class=\"dropdown-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"item-icon bg-warning\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-settings mx-0\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"font-weight-normal\">Settings</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"font-weight-light small-text mb-0 text-muted\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tPrivate message</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a> <a class=\"dropdown-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"item-icon bg-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-account-box mx-0\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"font-weight-normal\">New user registration</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"font-weight-light small-text mb-0 text-muted\">2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdays ago</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- 알림 아이콘 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<button\r\n");
      out.write("\t\t\t\t\tclass=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\"\r\n");
      out.write("\t\t\t\t\ttype=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("\t\t\t\t\t<span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- headerMemberModifyPassword -->\r\n");
      out.write("\t\t<div class=\"modal\" id=\"headerMemberModifyPasswordModal\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<!-- Modal Header -->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"modal-title\">회원 정보</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Modal body -->\r\n");
      out.write("\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">회원 정보</font>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label> <font style=\"vertical-align: inherit;\">비밀번호 확인</font></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"MEMBER_PWD\" id=\"headerMemberModifyPassword\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"headermemberhiddenid\" value =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Memberlogin.MEMBER_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" id=\"headerMemberModifyPasswordBtn\" name=\"headerMemberModifyPasswordBtn\" class=\"btn btn-info\" onclick=\"headerMemberModifyPasswordCheck(headermemberhiddenid.value,headerMemberModifyPassword.value);\">확인</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" id=\"headerMemberModifyPasswordclose\" class=\"btn btn-success\">닫기</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- headerMemberModifyModal -->\r\n");
      out.write("\t\t<div class=\"modal\" id=\"headerMemberModifyModal\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Modal Header -->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"modal-title\">회원 정보</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Modal body -->\r\n");
      out.write("\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font style=\"vertical-align: inherit;\">회원 정보</font>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<form class=\"forms-sample\" name=\"headermembermodify\" method=\"post\" autocomplete=\"off\" action=\"/member/MemberModify2\" onsubmit=\"return headervalidate();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label> <font style=\"vertical-align: inherit;\">아이디</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label> <input name=\"MEMBER_ID\" id=\"HeaderMEMBER_ID\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Memberlogin.MEMBER_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label> <font style=\"vertical-align: inherit;\">이름</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label> <input name=\"MEMBER_NAME\" id=\"HeaderMEMBER_NAME\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Memberlogin.MEMBER_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label> <font style=\"vertical-align: inherit;\">비밀번호</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label> <input name=\"MEMBER_PWD\" id=\"HeaderMEMBER_PWD\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" style='ime-mode:disabled' maxlength=\"12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label> <font style=\"vertical-align: inherit;\">이메일</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label> <input name=\"MEMBER_EMAIL\" id=\"HeaderMEMBER_EMAIL\" type=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Memberlogin.MEMBER_EMAIL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxlength=\"50\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label> <font style=\"vertical-align: inherit;\">핸드폰\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t번호</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label> <input name=\"MEMBER_PHONE_NUMBER\" id=\"HeaderMEMBER_PHONE_NUMBER\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"tel\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Memberlogin.MEMBER_PHONE_NUMBER}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" id=\"headermodifyBtn\" name=\"headermodifyBtn\" class=\"btn btn-info\">수정</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" id=\"headermodifyclose\" class=\"btn btn-success\">닫기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- partial -->\r\n");
      out.write("\t\t<div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- partial:partials/_sidebar.html -->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("li{list-style: none;}\r\n");
      out.write(".accordion_wrap a{cursor:pointer;}\r\n");
      out.write(".accordion_wrap .accordion_content{display:none;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"sidebar sidebar-offcanvas\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<ul class=\"nav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/\">\r\n");
      out.write("\t\t\t\t\t<i class=\"mdi mdi-home menu-icon\"></i> <span class=\"menu-title\">임의 창</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"nav-item open accordion_wrap\"><a class=\"nav-link\"> \r\n");
      out.write("\t\t\t<i class=\"mdi mdi-file-document-box-outline menu-icon\"></i> \r\n");
      out.write("\t\t\t<span class=\"menu-title\">재고</span></a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"accordion_content\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/product/productList\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"mdi mdi-file-document-box-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu-title\">상품 재고</span>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/book/bookList\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"mdi mdi-file-document-box-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu-title\">책 재고</span>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"nav-item open accordion_wrap\"><a class=\"nav-link\"> \r\n");
      out.write("\t\t\t<i class=\"mdi mdi-file-document-box-outline menu-icon\"></i> \r\n");
      out.write("\t\t\t<span class=\"menu-title\">매출</span></a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"accordion_content\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/managerpos/managerpos\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"mdi mdi-grid-large menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu-title\">포스 화면</span>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/settlement/settlementlist\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"mdi mdi-file-document-box-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu-title\">정산</span>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("<!-- \t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\thref=\"/managerpos/managerpos\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"mdi mdi-grid-large menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"menu-title\">포스 화면</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\thref=\"/settlement/settlementlist\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"mdi mdi-file-document-box-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"menu-title\">정산</span> -->\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\thref=\"/loss/losslist\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"mdi mdi-file-document-box-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"menu-title\">손실</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"/salesstatistics/saleslist\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"mdi mdi-file-document-box-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"menu-title\">매출</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t<a class=\"nav-link\" href=\"/salesstatistics/salesstatisticslist\">\r\n");
      out.write("\t\t\t\t\t<i class=\"mdi mdi-chart-pie menu-icon\"></i>\r\n");
      out.write("\t\t\t\t\t<span class=\"menu-title\">매출 통계</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</li>\t\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\thref=\"/CustomerCenter/boardList\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-file-document-box-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"menu-title\">건의 게시판</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\thref=\"/member/MemberList\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-file-document-box-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"menu-title\">회원 관리</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\thref=\"/userOrderManager/orderManager\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-file-document-box-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\t\tclass=\"menu-title\">상품 사용자뷰 관리</span> \r\n");
      out.write("\t\t\t</a></li>\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(\".accordion_wrap > a\").click(function(){\r\n");
      out.write("    // 현재 클릭한 태그가 a 이기 때문에\r\n");
      out.write("    // a 옆의 태그중 ul 태그에 hide 클래스 태그를 넣던지 빼던지 한다.\r\n");
      out.write("    $(this).next(\"ul\").toggleClass(\"accordion_content\");\r\n");
      out.write("    console.log(\"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\");\r\n");
      out.write("});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- partial -->\r\n");
      out.write("<div class=\"main-panel\">\r\n");
      out.write("\t<div class=\"content-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12 grid-margin\">\r\n");
      out.write("\t\t\t\t<div class=\"d-flex justify-content-between flex-wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"d-flex align-items-end flex-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mr-md-3 mr-xl-5\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Welcome back,</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"mb-md-0\">Your analytics dashboard template.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"mdi mdi-home text-muted hover-cursor\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-muted mb-0 hover-cursor\">&nbsp;/&nbsp;Dashboard&nbsp;/&nbsp;</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-primary mb-0 hover-cursor\">Analytics</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"d-flex justify-content-between align-items-end flex-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-light bg-white btn-icon mr-3 d-none d-md-block \">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"mdi mdi-download text-muted\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-light bg-white btn-icon mr-3 mt-2 mt-xl-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"mdi mdi-clock-outline text-muted\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-light bg-white btn-icon mr-3 mt-2 mt-xl-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"mdi mdi-plus text-muted\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary mt-2 mt-xl-0\">Generate\r\n");
      out.write("\t\t\t\t\t\t\treport</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\" id=\"proBanner\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12 grid-margin\">\r\n");
      out.write("\t\t\t\t<div class=\"card bg-gradient-primary border-0\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"card-body py-3 px-4 d-flex align-items-center justify-content-between flex-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"mb-0 text-white font-weight-medium\">Like what you\r\n");
      out.write("\t\t\t\t\t\t\tsee? Checkout our premium version for more.</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://github.com/Urbanui/MajesticAdmin-Free-Bootstrap-Admin-Template\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"_blank\" class=\"btn btn-outline-light mr-2\">Download\r\n");
      out.write("\t\t\t\t\t\t\t\tfree version</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"http://www.urbanui.com/majestic-admin-pro/template/\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"_blank\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-outline-light mr-2 bg-gradient-danger border-0\">Upgrade\r\n");
      out.write("\t\t\t\t\t\t\t\tto Pro</a>\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"bannerClose\" class=\"btn border-0 p-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"mdi mdi-close text-white\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12 grid-margin stretch-card\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body dashboard-tabs p-0\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-tabs px-4\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"overview-tab\" data-toggle=\"tab\" href=\"#overview\" role=\"tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-controls=\"overview\" aria-selected=\"true\">Overview</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" id=\"sales-tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tab\" href=\"#sales\" role=\"tab\" aria-controls=\"sales\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-selected=\"false\">Sales</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" id=\"purchases-tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"tab\" href=\"#purchases\" role=\"tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-controls=\"purchases\" aria-selected=\"false\">Purchases</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-content py-0 px-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab-pane fade show active\" id=\"overview\"\r\n");
      out.write("\t\t\t\t\t\t\t\trole=\"tabpanel\" aria-labelledby=\"overview-tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex flex-wrap justify-content-xl-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-none d-xl-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-calendar-heart icon-lg mr-3 text-primary\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Start date</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-secondary dropdown-toggle p-0 bg-transparent border-0 text-dark shadow-none font-weight-medium\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"#\" role=\"button\" id=\"dropdownMenuLinkA\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mb-0 d-inline-block\">26 Jul 2018</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"dropdown-menu\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-labelledby=\"dropdownMenuLinkA\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">12 Aug 2018</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">22 Sep 2018</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">21 Oct 2018</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-currency-usd mr-3 icon-lg text-danger\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Revenue</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mr-2 mb-0\">$577545</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-eye mr-3 icon-lg text-success\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Total views</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mr-2 mb-0\">9833550</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-download mr-3 icon-lg text-warning\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Downloads</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mr-2 mb-0\">2233783</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex py-3 border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-flag mr-3 icon-lg text-danger\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Flagged</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mr-2 mb-0\">3497843</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab-pane fade\" id=\"sales\" role=\"tabpanel\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"sales-tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex flex-wrap justify-content-xl-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-none d-xl-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-calendar-heart icon-lg mr-3 text-primary\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Start date</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-secondary dropdown-toggle p-0 bg-transparent border-0 text-dark shadow-none font-weight-medium\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"#\" role=\"button\" id=\"dropdownMenuLinkA\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mb-0 d-inline-block\">26 Jul 2018</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"dropdown-menu\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-labelledby=\"dropdownMenuLinkA\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">12 Aug 2018</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">22 Sep 2018</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">21 Oct 2018</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-download mr-3 icon-lg text-warning\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Downloads</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mr-2 mb-0\">2233783</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-eye mr-3 icon-lg text-success\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Total views</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mr-2 mb-0\">9833550</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-currency-usd mr-3 icon-lg text-danger\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Revenue</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mr-2 mb-0\">$577545</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex py-3 border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-flag mr-3 icon-lg text-danger\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Flagged</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mr-2 mb-0\">3497843</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab-pane fade\" id=\"purchases\" role=\"tabpanel\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-labelledby=\"purchases-tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex flex-wrap justify-content-xl-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-none d-xl-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-calendar-heart icon-lg mr-3 text-primary\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Start date</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-secondary dropdown-toggle p-0 bg-transparent border-0 text-dark shadow-none font-weight-medium\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"#\" role=\"button\" id=\"dropdownMenuLinkA\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mb-0 d-inline-block\">26 Jul 2018</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"dropdown-menu\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taria-labelledby=\"dropdownMenuLinkA\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">12 Aug 2018</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">22 Sep 2018</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">21 Oct 2018</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-currency-usd mr-3 icon-lg text-danger\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Revenue</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mr-2 mb-0\">$577545</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-eye mr-3 icon-lg text-success\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Total views</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mr-2 mb-0\">9833550</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-download mr-3 icon-lg text-warning\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Downloads</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mr-2 mb-0\">2233783</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-flex py-3 border-md-right flex-grow-1 align-items-center justify-content-center p-3 item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-flag mr-3 icon-lg text-danger\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-column justify-content-around\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"mb-1 text-muted\">Flagged</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"mr-2 mb-0\">3497843</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-7 grid-margin stretch-card\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-title\">Cash deposits</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"mb-4\">To start a blog, think of a topic about and\r\n");
      out.write("\t\t\t\t\t\t\tfirst brainstorm party is ways to write details</p>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"cash-deposits-chart-legend\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"d-flex justify-content-center pt-3\"></div>\r\n");
      out.write("\t\t\t\t\t\t<canvas id=\"cash-deposits-chart\"></canvas>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-5 grid-margin stretch-card\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-title\">Total sales</p>\r\n");
      out.write("\t\t\t\t\t\t<h1>$ 28835</h1>\r\n");
      out.write("\t\t\t\t\t\t<h4>Gross sales over the years</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">Today, many people rely on computers to\r\n");
      out.write("\t\t\t\t\t\t\tdo homework, work, and create or store useful information.\r\n");
      out.write("\t\t\t\t\t\t\tTherefore, it is important</p>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"total-sales-chart-legend\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<canvas id=\"total-sales-chart\"></canvas>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12 stretch-card\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-title\">Recent Purchases</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<table id=\"recent-purchases-listing\" class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Status report</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Office</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Gross amount</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Jeremy Ortega</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Levelled up</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Catalinaborough</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$790</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>06 Jan 2018</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$2274253</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Alvin Fisher</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Ui design completed</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>East Mayra</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$23230</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>18 Jul 2018</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$83127</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Emily Cunningham</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>support</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Makennaton</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$939</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>16 Jul 2018</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$29177</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Minnie Farmer</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>support</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Agustinaborough</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$30</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>30 Apr 2018</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$44617</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Betty Hunt</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Ui design not completed</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Lake Sandrafort</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$571</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>25 Jun 2018</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$78952</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Myrtie Lambert</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Ui design completed</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Cassinbury</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$36</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>05 Nov 2018</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$36422</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Jacob Kennedy</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>New project</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Cletaborough</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$314</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>12 Jul 2018</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$34167</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Ernest Wade</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Levelled up</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>West Fidelmouth</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$484</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>08 Sep 2018</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>$50862</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- content-wrapper ends -->\r\n");
      out.write("\t<!-- partial:partials/_footer.html -->\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tclass=\"d-sm-flex justify-content-center justify-content-sm-between\">\r\n");
      out.write("\t\t\t<span\r\n");
      out.write("\t\t\t\tclass=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright\r\n");
      out.write("\t\t\t\tï¿½ 2018 <a href=\"https://www.urbanui.com/\" target=\"_blank\">Urbanui</a>.\r\n");
      out.write("\t\t\t\tAll rights reserved.\r\n");
      out.write("\t\t\t</span> <span\r\n");
      out.write("\t\t\t\tclass=\"float-none float-sm-right d-block mt-1 mt-sm-0 text-center\">Hand-crafted\r\n");
      out.write("\t\t\t\t& made with <i class=\"mdi mdi-heart text-danger\"></i>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- partial -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- main-panel ends -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- page-body-wrapper ends -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- container-scroller -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/./includes/header.jsp(164,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty Memberlogin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<li class=\"nav-item nav-profile dropdown\"><a\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\"\r\n");
          out.write("\t\t\t\t\t\t\tid=\"profileDropdown\"><span class=\"hidden-xs\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Memberlogin.MEMBER_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right navbar-dropdown\"\r\n");
          out.write("\t\t\t\t\t\t\t\taria-labelledby=\"profileDropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" onclick='javascript:headermembermodifyBtn()'> <i\r\n");
          out.write("\t\t\t\t\t\t\t\t\tclass=\"mdi mdi-settings text-primary\"></i> 회원정보\r\n");
          out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-item\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/MemberLogout\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-logout text-primary\"></i> 로그아웃\r\n");
          out.write("\t\t\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t</div></li>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/./includes/header.jsp(179,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty Employeelogin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<li class=\"nav-item nav-profile dropdown\"><a\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\"\r\n");
          out.write("\t\t\t\t\t\t\tid=\"profileDropdown\"><span class=\"hidden-xs\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Employeelogin.EMPLOYEE_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right navbar-dropdown\"\r\n");
          out.write("\t\t\t\t\t\t\t\taria-labelledby=\"profileDropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/EmployeeLogout\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-logout text-primary\"></i> 로그아웃\r\n");
          out.write("\t\t\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t</div></li>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
