/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-10-22 09:17:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/1027/Documents/GitHub/comic_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/comic_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/./includes/userHeader.jsp", Long.valueOf(1571735347409L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1566355891683L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Comic Clerk</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resources/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resources/vendors/base/vendor.bundle.base.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resources/vendors/datatables.net-bs4/dataTables.bootstrap4.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom Fonts -->\r\n");
      out.write("<link href=\"/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"/resources/vendor/simple-line-icons/css/simple-line-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core JavaScript -->\r\n");
      out.write("<script src=\"/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Plugin JavaScript -->\r\n");
      out.write("<script src=\"/resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/base/vendor.bundle.base.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/datatables.net/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"/resources/vendors/datatables.net-bs4/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/vendors/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/vendors/base/vendor.bundle.base.css\">\r\n");
      out.write("<link rel=\"stylesheet\"href=\"/resources/vendors/datatables.net-bs4/dataTables.bootstrap4.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom scripts for this template -->\r\n");
      out.write("<script src=\"/resources/js/stylish-portfolio.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/off-canvas.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/hoverable-collapse.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/template.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/dashboard.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/data-table.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/sockjs/1/sockjs.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/userWebsocket.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"/resources/css/stylish-portfolio.min.css?ver=1\" rel=\"stylesheet\"> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".content-wrapper {\r\n");
      out.write("\tpadding-top: 150px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<div class=\"main-penal\">\r\n");
      out.write("\t\t<div style=\"background-color: #37363a; height: 150px;\">\r\n");
      out.write("\t\t\t<img src=\"/resources/images/comic_image.png\" alt=\"\" style=\"width: 200px; height: 100px; margin-left:40px; margin-top:20px; \"/>\r\n");
      out.write("\t\t\t<div style=\"width: 1000px; float:right; height: 100px; color:#f4e362; margin-top:50px; font-size: 50px;\">\r\n");
      out.write("\t\t\t 여기는 편의를 위한 임시 창입니다\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br/><br/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t<!-- <div class=\"content-section-heading text-center\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"mb-5\">코믹서기에 오신걸 환영합니다</h2> \r\n");
      out.write("\t\t\t\t</div>  -->\r\n");
      out.write("\t\t\t\t<div class=\"row no-gutters\"> \r\n");
      out.write("\t\t\t\t\t<!-- <div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-item\" name=\"roomMove\" value=\"1\"> <span class=\"caption\"> <span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>1번방</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-0\">A yellow pencil with envelopes on a clean, blue backdrop!</p>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</span> <img class=\"img-fluid\" src=\"/resources/images/portfolio-1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-item\" name=\"roomMove\" value=\"1\"> <img class=\"img-fluid\" src=\"/resources/images/room-icon.png\" alt=\"\" style=\"width:370px; height:250px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"caption\"> \r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 style=\"margin-left:75px; margin-top:100px;\">1번방</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-item\" name=\"roomMove\" value=\"2\"> <img class=\"img-fluid\" src=\"/resources/images/room-icon.png\" alt=\"\" style=\"width:370px; height:250px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"caption\"> \r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 style=\"margin-left:75px; margin-top:100px;\">2번방</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-item\" name=\"roomMove\" value=\"3\"> <img class=\"img-fluid\" src=\"/resources/images/room-icon.png\" alt=\"\" style=\"width:370px; height:250px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"caption\"> \r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 style=\"margin-left:75px; margin-top:100px;\">3번방</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-item\" name=\"roomMove\" value=\"4\"> <img class=\"img-fluid\" src=\"/resources/images/room-icon.png\" alt=\"\" style=\"width:370px; height:250px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"caption\"> \r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 style=\"margin-left:75px; margin-top:100px;\">4번방</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\t \r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a class=\"portfolio-item\" name=\"roomMove\" value=\"5\"> <img class=\"img-fluid\" src=\"/resources/images/room-icon.png\" alt=\"\" style=\"width:370px; height:250px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"caption\"> \r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 style=\"margin-left:75px; margin-top:100px;\">5번방</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"portfolio-item\" name=\"erpMain\"><img class=\"img-fluid\" src=\"/resources/images/settingIcon.png\" alt=\"\" style=\"width:370px; height:250px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"caption\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"caption-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 style=\"margin-left:90px; margin-top:50px; height: 40px;\">ERP</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t\t</a>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- hidden form -->\r\n");
      out.write("\t<form id=\"operForm\"></form>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("let ws = new WebSocket(\"ws://localhost:8080/echo\");\r\n");
      out.write("socket = ws;\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tvar operForm = $(\"#operForm\");\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"a[name='roomMove']\").on(\"click\", function(e){\r\n");
      out.write("\t\toperForm.append(\"<input type='hidden' name='roomNum' value='\" + $(this).attr('value') + \"'>\");\r\n");
      out.write("\t\toperForm.attr(\"method\", \"post\");\r\n");
      out.write("\t\toperForm.attr(\"action\",\"/userView/main\");\r\n");
      out.write("\t\toperForm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"a[name='erpMain']\").on(\"click\", function(e){\r\n");
      out.write("\t\toperForm.attr(\"method\", \"get\");\r\n");
      out.write("\t\toperForm.attr(\"action\",\"/managerpos/managerpos\");\r\n");
      out.write("\t\toperForm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
